### ISSUE TITLE
Question regarding single bulbs

### ISSUE THREAD

**Issue by lukewelsh** [kame31/Kontrol#1]
I'm trying to set up control of individual lights using Max MSP, and by sending the command for the light name, it is controlling all my colour bulbs, the light name in the Kontrol app is Music room light, and I've used both MUSIC_ROOM_LIGHT, both upper and lowercase, without the underscores, and every combination I can think of but it's still controlling all lights instead of just the one. I have very little experience with any programming so any help would be appreciated

**Comment by kame31** [comment]
Simply choose names for your light-bulbs without spaces.
